#-----------------------------------
#USER FLAGS
#-----------------------------------
#default input file and output directory

infile:  "data/ts2_0.GeoPIXE"   #assign input file
outdir: "out/"

#infile: "/mnt/d/DATA/XFMDATA/2022/dimarco_zoey/sections2_25um_221101/full_25um.GeoPIXE"      #input (abs or relative to script)
#outdir: '/mnt/d/DATA/XFMDATA/2022/dimarco_zoey/sections2_25um_221101/S4/'                 #output directory (abs or relative to script)

PARSEMAP: False   #load spectrum-by-pixel data

chunksize: 100    #size in Mb to load into memory at a time

DOCOLOURS: False   #run colourmap
DOCLUST: False     #run clustering

#recalc flags
FORCEPARSE: True     #always parse datafile
FORCERED: True       #always recalc dimensionality reduction
FORCEKMEANS: True    #always recalc kmeans 

#SUBMAP
WRITESUBMAP: True    #write a submap
submap_x: #x coordinates for writing submap
  - 0   
  - 0
submap_y: #y coordinates for writing submap
  - 0
  - 0