#-----------------------------------
#USER FLAGS
#-----------------------------------
#default input file and output directory

infile:  
- "/mnt/d/DATA/XFMDATA/2023/Lachlan/REFERENCE/IXRF_block_230120/40-200/scan256.GeoPIXE"   #assign input file

outdir: 
- "/mnt/d/DATA/XFMDATA/2023/Lachlan/REFERENCE/IXRF_block_230120/40-200/PXVALS"

PARSEMAP: True   #load spectrum-by-pixel data

chunksize: 1000    #size in Mb to load into memory at a time

DOCOLOURS: True   #run colourmap
DOCLUST: True     #run clustering
DODTCALCS: True    #generate deadtime plots

#recalc flags
FORCEPARSE: True     #always parse datafile
FORCERED: True       #always recalc dimensionality reduction
FORCEKMEANS: True    #always recalc kmeans 

#SUBMAP
WRITESUBMAP: False    #write a submap
submap_x: #x coordinates for writing submap
  - 0
  - 0
submap_y: #y coordinates for writing submap
  - 0
  - 0