#-----------------------------------
#HARDCODED CONSTANTS (eg. filetype properties)
#-----------------------------------
FTYPE: ".GeoPIXE"    #valid: ".GeoPIXE"

PXHEADERLEN: 16  #pixel header size
BYTESPERCHAN: 4
PXFLAG: 'DP'
NCHAN: 4096
ESTEP: 0.01
CHARENCODE: 'utf-8'
MBCONV: 1048576 #bytes per Mb
#-----------------------------------
#USER FLAGS
#-----------------------------------
#default input file and output directory

infile:  "data/dw_ts2.GeoPIXE"    #assign input file
#infile: "/mnt/d/DATA/XFMDATA/2022/Simpson_Brenainn/slides_220712/slides_45um.GeoPIXE"      #input (abs or relative to script)
outdir: 'out'                 #output directory (abs or relative to script)

#SUBMAP
SUBMAPONLY: True   #do not create pixelseries, just write submap and exit
DOSUBMAP: True    #write a submap
submap_x1: 50   #coordinates for writing submap
submap_y1: 0  ##BS *-900-1918-*
submap_x2: 150
submap_y2: 0

#recalc flags
FORCEPARSE: True     #always parse datafile
FORCERED: True       #always recalc dimensionality reduction
FORCEKMEANS: True    #always recalc kmeans 

#-----------------------------------
#FLAGS
#-----------------------------------

DOCOLOURS: True   #run colourmap1
DOCLUST: True     #run clustering

SEPSUMSPEC: True #sum class spectra
SAVEPXSPEC: True #save pixel spectra

DOBG: False      #apply background fitting
LOWBGADJUST: False    #tweak background for low signal data

SHORTRUN: False  #stop after first X% of pixels
shortpct: 20     #% of lines to run in short config

CMAP: 'Set1' #default colourmap for clusters

#debug flags
DEBUG: False     #debug flag (pixels)
DEBUG2: False    #second-level debug flag (channels)


#-----------------------------------
#VARIABLES
#-----------------------------------


chunksize: 104857600   #100 Mb
#chunksize: 1073741824 #1 Gb
#chunksize: 2147483648  #2 Gb

#infile: "geo_nfpy11.GeoPIXE"
#infile: "geo_ln_chle.GeoPIXE"
#infile: "geo_dwb12-2.GeoPIXE"
#infile: "concrete.GeoPIXE"
#infile:  "converted.GeoPIXE"

#infile:  "geo2.GeoPIXE"    #assign input file

outfile: "pxspec"
convext: "_sub"

#instrument config
detid: 0  #detector ID - not currently used
nclust: 6       #no of clusters

#figure params (currently not used)
figx: 20         #cm width of figure
figy: 10         #cm height of figure
smallfont: 8   #default small font
medfont: 10    #default medium font
lgfont: 12     #default large font
lwidth: 1      #default linewidth
bwidth: 1      #default border width

#colour flags:
MIN_E: 1.04      #minimum energy of interest
MIN_XE: -5       #extended minimum x for ir
ELASTIC: 17.44   #energy of tube Ka
EOFFSET: 3.0
MAX_E: 30        #maximum energy of interest
SDS: 9           #standard deviations
RGBLOG: False     #map RGB as log of intensity
NCOLS: 5         #no. colours
#these should all be refactored into config, really

